### ISSUE TITLE
还请添加gh-page的发布教程

### ISSUE THREAD

**Issue by hoochanlon** [zhangjikai/gitbook-use#10]
写得的确很不错，但是少了gh-page的发布教程，略显不足

**Comment by zhangjikai** [comment]
现在我也没找到特别好的办法，我都是用 GitBook 生成html 文件以后， 将 html 文件复制过来， 然后 push 上来。

**Comment by hoochanlon** [comment]
应该可以试着锦上添花，毕竟折腾这么久到头来却是离线部署，对于初学者可能会有些失望

另外 `theme-default": {"showLevel": true}`加上`pluginsConfig`比较好，不看最后的配置文件的话，很容易让人误解而直接添加了

**Comment by zhangjikai** [comment]
我确实没有找到太好的解决办法，我之前都是写个脚本，自动完成这个过程，不过还是有点麻烦，所以我现在转战 [docsify](https://docsify.js.org/#/) 了，功能虽然没有gitbook 多，但是不用再编译了，而且可以满足我的需求，有兴趣的话你可以看看。

**Comment by hoochanlon** [comment]
这应该是国人写的吧，一般像这种且目前用的人不多，基本上没啥中文支持的
