### ISSUE TITLE
hello , would you have a will to help me something about gitbook ,? if possible , contact me  by qq 876910486,thank yuou 

### ISSUE THREAD

**Issue by wayward-man** [zhangjikai/gitbook-use#13]

**Comment by zhangjikai** [comment]
Hello, if you have any question, you can leave a message here.

**Comment by wayward-man** [comment]
Error: ENOENT: no such file or directory, stat 'C:\Users\zhangxiaofei\Desktop\gitbook\book\_book\gitbook\gitbook-plugin-fontsettings\fontsettings.js'
， 这个问题，经常出现，你知道 啥原因吗，官网 好多人问，没看到恢复

**Comment by zhangjikai** [comment]
这个好像和 windows 系统有关，具体的解决办法我也不知道。
