### ISSUE TITLE
gitbook -v显示not found

### ISSUE THREAD

**Issue by SanShiSir** [zhangjikai/gitbook-use#2]
安装完gitbook-cli之后，我的命令行，gitbook -v根本不显示版本，显示bash: gitbook: command not found这是什么情况，不会是因为win7吧

**Comment by zhangjikai** [comment]
重启下电脑试试, 如果还是不行, 你看看有没有把存放 nodejs 全局包的文件夹路径加入到 path 当中

**Comment by SanShiSir** [comment]
发现这个问题了，NODE安装在d盘，gitbook-cli就安装在NODE/node_global下了，但是，之前安装webpack也是global啊，确实在c/user~下，很奇怪啊，
