### ISSUE TITLE
github +gitbook 插件问题请教

### ISSUE THREAD

**Issue by Esusi** [zhangjikai/gitbook-use#4]
你好，我看了你的文章，结合我的项目，我有问题请教：
        我在GitHub托管了gitbook内容（已经和gitbook关联），现在我本地按你的book.json在本地安装了插件，之后用github客户端同步时卡死啦，我觉得哪不对，向问问你，怎么才能在我托管在gitbook上的项目也安装有我本地安装的这些插件！！！劳烦啦！！！

**Comment by zhangjikai** [comment]
我没太明白你的意思，如果是 gitbook 网站上的项目，只要本地在 book.json 里配置了相关插件，gitbook 网站上的项目会自动加载相关插件并进行编译。至于 gitbook 和 github 相互关联，我没有弄过，不太清楚。

**Comment by Esusi** [comment]
好的，谢谢，我试试
