### ISSUE TITLE
安装anchor-navigation-ex插件，页面不显示回到顶部和右悬浮，请问这个怎么解决？

### ISSUE THREAD

**Issue by codePanda0916** [zhangjikai/gitbook-use#5]
安装anchor-navigation-ex插件，页面不显示回到顶部和右悬浮，请问这个怎么解决？

**Comment by zhangjikai** [comment]
刚刚试了一下，anchor-navigation-ex 可以正常工作。你方便把你的 gitbook 项目发我一下么，me@zhangjikai.com 。如果不方便的话，你可以去  [anchor-navigation-ex 的项目](https://github.com/zq99299/gitbook-plugin-anchor-navigation-ex) 下提个issue。

**Comment by codePanda0916** [comment]
谢谢，刚刚测试可以啦。还有一个问题，就是右上角的导航是否可以去掉。只显示右下角的回到顶部图标。
