### ISSUE TITLE
求助关于pdf目录

### ISSUE THREAD

**Issue by bubifengyun** [zhangjikai/gitbook-use#6]
我用 gitbook 写了一些笔记，生成 PDF 文件。页码都是正常显示的。但是目录显示的是英文，而且页码都是 1.xx 2.xx 之类的。不是正常页码，可有什么插件使他成为中文目录，且页码是显示的正常数字页码，而不是类似节号的 1.xx 。谢谢啦。

我的笔记地址：https://github.com/bubifengyun/book-yii2-dev-process

**Comment by zhangjikai** [comment]
我查了一下，这个好像和 calibre 有关，目前的解决方法就是更改 gitbook 生成 pdf 时使用的转换器，下面是几个相关的链接：
* https://github.com/GitbookIO/gitbook/issues/1223
* https://github.com/GitbookIO/gitbook/issues/1470
* https://github.com/lwchkg/gitbook-pdfgen

我用 wkhtmltopdf 试了一下，虽然目录页码显示正确了，但是排版有点乱，你可以试一下看看效果。

**Comment by bubifengyun** [comment]
万分感谢，还让您折腾去查找。我试试，再来告诉您。

**Comment by daniellauyu** [comment]
还有这个问题啊，楼上三位大佬解决这个问题没啊

**Comment by bubifengyun** [comment]
https://github.com/bubifengyun/deepin-bible  换到bookdown 模板。上面有更详细的使用介绍。都是用 markdown 写作。如有不懂，欢迎留言。在 release 有可见 pdf 文件。自认为设计有点精美。自夸啦。

**Comment by bubifengyun** [comment]
https://github.com/bubifengyun/deepin-bible  换到bookdown 模板。上面有更详细的使用介绍。都是用 markdown 写作。如有不懂，欢迎留言。在 release 有可见 pdf 文件。自认为设计有点精美。自夸啦。

**Comment by bubifengyun** [comment]
https://github.com/bubifengyun/deepin-bible  换到bookdown 模板。上面有更详细的使用介绍。都是用 markdown 写作。如有不懂，欢迎留言。在 release 有可见 pdf 文件。自认为设计有点精美。自夸啦。

**Comment by xiayuenice163** [comment]
我用 gitbook 写了一些笔记，生成 PDF 文件。页码都是正常显示的。但是目录显示的是英文，而且页码都是 1.xx 2.xx 之类的。不是正常页码，可有什么插件使他成为中文目录，且页码是显示的正常数字页码，而不是类似节号的 1.xx。我也出现这个问题，请问怎么解决

**Comment by bubifengyun** [comment]
这个用gitbook的，我一直没有解决。但是改用bookdown这些问题都不存在了。且bookdown支持生成gitbook格式，算了，不发广告了，毕竟这是gitbook地盘。
