### ISSUE TITLE
搜索框内的placeholder文字怎么修改

### ISSUE THREAD

**Issue by waitkafuka** [zhangjikai/gitbook-use#9]
请问老兄，这里的提示文字怎么修改？如图：
![image](https://user-images.githubusercontent.com/8555018/37145142-142d1146-22fb-11e8-9bf5-00d7d3f1d3b4.png)

**Comment by zhangjikai** [comment]
在 book.json 里设置 `"language" : "zh-hans",`  可以显示中文的提示

**Comment by waitkafuka** [comment]
搞定，多谢！

**Comment by waitkafuka** [comment]
搞定，多谢！

**Comment by lucumt** [comment]
> 在 book.json 里设置 `"language" : "zh-hans",` 可以显示中文的提示

@zhangjikai 我用的是`GitBook 3.2.3`，在`books.json`中添加 `"language" : "zh-hans",`或 `"language" : "zh",`都不生效，请问这种如何处理呢，谢谢
